version: '3'

services:

  db:
    image: postgres:14-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: cryptic_auth
      POSTGRES_DB: cryptic_auth
      POSTGRES_PASSWORD: cryptic_auth

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"

  prometheus:
    image: prom/prometheus:v2.34.0
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml